### ISSUE TITLE
LoadMapSettings crash

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#22]
Nullpointer access:

```
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x0000556e5ee1ba5d in str_length (str=str@entry=0x0) at /home/teeworlds/src7/master/src/base/system.c:1833
#2  0x0000556e5edca5c0 in CGameContext::LoadMapSettings (this=this@entry=0x7fd802d31010)
    at /home/teeworlds/src7/master/src/game/server/gamecontext.cpp:2355
#3  0x0000556e5edcac8d in CGameContext::OnInit (this=0x7fd802d31010)
    at /home/teeworlds/src7/master/src/game/server/gamecontext.cpp:1959
#4  0x0000556e5edab028 in CServer::Run (this=0x7fd803562010)
    at /home/teeworlds/src7/master/src/engine/server/server.h:82
#5  0x0000556e5eda46d9 in main (argc=3, argv=0x7fff3e395898)
    at /home/teeworlds/src7/master/src/engine/server/server.cpp:1979
```

**Comment by def-** [comment]
Ok, looks like my converter script is sometimes writing out garbage for the map settings.

**Comment by def-** [comment]
Happens with Absurd 4 for example.

**Comment by def-** [comment]
fixed.
