### ISSUE TITLE
Crash in src/game/server/entities/character.cpp:1506

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#54]
```
Core was generated by `./DDNet7-Server -f servers/9304.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CCharacter::HandleTiles (this=this@entry=0x5570b89f6d48 <ms_PoolDataCCharacter+5160>, Index=92213)
    at /home/teeworlds/src7/master/src/game/server/entities/character.cpp:1506
1506		if (((m_TileIndex == TILE_TELE_GUN_ENABLE) || (m_TileFIndex == TILE_TELE_GUN_ENABLE)) && !m_HasTeleGun)
[Current thread is 1 (Thread 0x7f76d957d980 (LWP 27720))]
(gdb) bt
#0  CCharacter::HandleTiles (this=this@entry=0x5570b89f6d48 <ms_PoolDataCCharacter+5160>, Index=92213)
    at /home/teeworlds/src7/master/src/game/server/entities/character.cpp:1506
#1  0x00005570b894520b in CCharacter::DDracePostCoreTick (this=0x5570b89f6d48 <ms_PoolDataCCharacter+5160>)
    at /home/teeworlds/src7/master/src/game/server/entities/character.cpp:1985
#2  0x00005570b89455a6 in CCharacter::Tick (this=0x5570b89f6d48 <ms_PoolDataCCharacter+5160>)
    at /home/teeworlds/src7/master/src/game/server/entities/character.cpp:747
#3  CCharacter::Tick (this=0x5570b89f6d48 <ms_PoolDataCCharacter+5160>)
    at /home/teeworlds/src7/master/src/game/server/entities/character.cpp:734
#4  0x00005570b895a30d in CGameWorld::Tick (this=this@entry=0x7f76d83cfc30)
    at /home/teeworlds/src7/master/src/game/server/gameworld.cpp:174
#5  0x00005570b8954552 in CGameContext::OnTick (this=0x7f76d83c1010)
    at /home/teeworlds/src7/master/src/game/server/gamecontext.cpp:581
#6  0x00005570b89318f5 in CServer::Run (this=0x7f76d8bf2010)
    at /home/teeworlds/src7/master/src/engine/server/server.h:82
#7  0x00005570b892acec in main (argc=3, argv=0x7fff1434c418)
    at /home/teeworlds/src7/master/src/engine/server/server.cpp:2000
```
Looks like a player disconnected at the same time, so it was probably deleted:

```
[2020-01-10 03:46:48][server]: player is ready. ClientID=9 addr=X:51237
[2020-01-10 03:46:48][server]: 'Seeba' -> 'Seeba'
[2020-01-10 03:46:49][server]: player has entered the game. ClientID=9 addr=X:51237
[2020-01-10 03:46:49][sql]: Getting best time done 
[2020-01-10 03:47:07][chat-command]: 1 used /pause
[2020-01-10 03:47:08][chat-command]: 1 used /pause
[2020-01-10 03:47:08][whisper]: 0:3:maría ester: soy sola tuyaa miamor
[2020-01-10 03:47:13][whisper]: 1:3:ʑɑяηɑђ: te amo bb
[2020-01-10 03:47:19][whisper]: 0:3:maría ester: te amo más
[2020-01-10 03:47:21][chat]: 2:1:Meta: lel
[2020-01-10 03:47:22][chat]: 3:1:вlυeвerry: Y AHORA?
[2020-01-10 03:47:23][chat]: 2:1:Meta: xdddddddddd
[2020-01-10 03:47:25][chat-command]: 3 used /spec
[2020-01-10 03:47:26][chat-command]: 2 used /spec
[2020-01-10 03:47:34][chat]: 3:1:вlυeвerry: no entiendo nada 
[2020-01-10 03:47:35][chat-command]: 3 used /spec
[2020-01-10 03:47:37][server]: client dropped. cid=3 addr=unknown type 0 reason='Error sending data'
[2020-01-10 03:47:37][game]: kill killer='3:0:вlυeвerry' victim='3:0:вlυeвerry' weapon=-3 special=0
```
Happened on Chile, will keep the core file in case we need to look closer.

**Comment by def-** [comment]
Haven't seen this anymore since the last update.
