### ISSUE TITLE
failing to load client textures

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet7#6]
```
[2019-11-28 13:49:49][client]: loaded map 'heavens'
[2019-11-28 13:49:49][datafile]: loading data index=0 size=10 uncompressed=10
[2019-11-28 13:49:49][game/png]: failed to open file. filename='mapres/bg_clou.png'
[2019-11-28 13:49:49][datafile]: loading data index=1 size=10 uncompressed=10
[2019-11-28 13:49:49][game/png]: failed to open file. filename='mapres/bg_clou.png'
[2019-11-28 13:49:49][datafile]: loading data index=2 size=10 uncompressed=10
[2019-11-28 13:49:49][game/png]: failed to open file. filename='mapres/bg_clou.png'
[2019-11-28 13:49:49][datafile]: loading data index=3 size=4 uncompressed=4
[2019-11-28 13:49:49][game/png]: failed to open file. filename='mapres/s�x<�.png'
```
![screenshot_2019-11-28_13-48-25](https://user-images.githubusercontent.com/20344300/69807611-06a75000-11e6-11ea-927e-4a5a30b3af21.png)

**Comment by fokkonaut** [comment]
This repository was only focused on the server, not the client. Unintended client bugs can happen here

**Comment by ChillerDragon** [comment]
@fokkonaut yes I know but fixing the client now would still be nice :)

**Comment by ChillerDragon** [comment]
So the menu map is fine the client fails to load mapres of any map and crashes on connection to servers:
```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x00005555556fe58c in CTeamsCore::CanCollide (this=0x0, ClientID1=-1, ClientID2=9) at /home/chiller/Desktop/git/ddnet7/src/game/teamscore.cpp:33
33		if (m_Team[ClientID1] == TEAM_SUPER || m_Team[ClientID2] == TEAM_SUPER || ClientID1 == ClientID2)
(gdb) bt
#0  0x00005555556fe58c in CTeamsCore::CanCollide (this=0x0, ClientID1=-1, ClientID2=9) at /home/chiller/Desktop/git/ddnet7/src/game/teamscore.cpp:33
#1  0x00005555556fa7ee in CCharacterCore::Tick (this=0x55555598f6b8, UseInput=false) at /home/chiller/Desktop/git/ddnet7/src/game/gamecore.cpp:397
#2  0x000055555567199a in CGameClient::OnPredict (this=0x55555598a8e0) at /home/chiller/Desktop/git/ddnet7/src/game/client/gameclient.cpp:1421
#3  0x00005555555cd774 in CClient::Update (this=0x7ffff48e3010) at /home/chiller/Desktop/git/ddnet7/src/engine/client/client.cpp:1685
#4  0x00005555555ceca4 in CClient::Run (this=0x7ffff48e3010) at /home/chiller/Desktop/git/ddnet7/src/engine/client/client.cpp:2058
#5  0x00005555555d0f7d in main (argc=1, argv=0x7fffffffda98) at /home/chiller/Desktop/git/ddnet7/src/engine/client/client.cpp:2664
```

**Comment by fokkonaut** [comment]
Of course it does, because there is no client side connection to this. Only serverside. Thats why I am saying it doesnt make sense to do this right now.
