### ISSUE TITLE
Crash CServer::UpdateClientRconCommands

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet7#77]
```
[2020-02-26 23:30:53][server]: player is ready. ClientID=0 addr=<{X.X.X.X:55722}>
[2020-02-26 23:30:53][server]: 'A' -> 'A'
[2020-02-26 23:30:53][server]: player has entered the game. ClientID=0 addr=<{X.X.X.X:55722}>
[2020-02-26 23:30:53][sql]: Getting best time done
[2020-02-26 23:30:53][server]: player is ready. ClientID=1 addr=<{X.X.X.X:56223}>
[2020-02-26 23:30:53][server]: 'X' -> 'X'
[2020-02-26 23:30:53][server]: player has entered the game. ClientID=1 addr=<{x.x.x.x:56223}>
[2020-02-26 23:30:53][sql]: Getting best time done
[2020-02-26 23:30:54][server]: client dropped. cid=0 addr=<{unknown type 0}> reason='Error sending data'
[2020-02-26 23:30:54][game]: kill killer='0:0:A' victim='0:0:A' weapon=-3 special=0

#0  0x00005555555a8a69 in CServer::UpdateClientRconCommands (this=0x7ffff62e8010) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:877
#1  0x00005555555ac1da in CServer::Run (this=0x7ffff62e8010) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:1608
#2  0x00005555555af75e in main (argc=2, argv=0x7fffffffe4d8) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:2386

```

**Comment by ChillerDragon** [comment]
```
#0  0x00005555555a8a69 in CServer::UpdateClientRconCommands (this=0x7ffff62e8010) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:877
        i = 0
        ConsoleAccessLevel = 0
        ClientID = 0
#1  0x00005555555ac1da in CServer::Run (this=0x7ffff62e8010) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:1608
        t = 1582756254342750
        NewTicks = 1
        ReportTime = 1582756254875523
        ReportInterval = 3
        Userdata = {m_pServer = 0x7ffff62e8010, m_aName = '\000' <repeats 31 times>}
        BindAddr = {type = 3, ip = '\000' <repeats 15 times>, port = 8360}
        aBuf = "version 0.7 802f1be60a05665f\000llection Server #1'\000\teUUU\000\000\000\060vUUU\000\000p\343\377\377\377\177\000\000[wcUUU\000\000\060\002zU\003\000\000\000p.vUUU\000\000\276\000fUUU\000\000\000\225\206z\277\266\275V\000\343\377\377\377\177\000\000\025PbUUU\000\000\000ErUUU\000\000\020", '\000' <repeats 15 times>, ",\000\000\000\000\000\000\000ogs/solo1/logs/solo1_2020-02-25_15-16-17"...
#2  0x00005555555af75e in main (argc=2, argv=0x7fffffffe4d8) at /opt/twserver/git/ddnet7/src/engine/server/server.cpp:2386
        UseDefaultConfig = false
        pServer = 0x7ffff62e8010
        pKernel = 0x555555762550
        FlagMask = 36
        pEngine = 0x555555762e70
        pEngineMap = 0x5555557291a0
        pGameServer = 0x7ffff5ab7010
        pConsole = 0x555555763790
        pEngineMasterServer = 0x555555799740
        pStorage = 0x555555799d10
        pConfig = 0x55555579c530
        Ret = 32767
rax            0x0                 0
rbx            0xffffffff          4294967295
rcx            0x0                 0
rdx            0x7ffff62e8010      140737323630608
rsi            0x555555674204      93824993411588
rdi            0x7ffff69eff00      140737331003136
rbp            0x7fffffffe150      0x7fffffffe150
rsp            0x7fffffffe130      0x7fffffffe130
r8             0xdf                223
r9             0x5555559b2090      93824996810896
r10            0x6                 6
r11            0x7ffffffdcb00      140737488210688
r12            0x7ffff6c105e0      140737333233120
r13            0x7fffffffe4d0      140737488348368
r14            0x0                 0
r15            0x0                 0
rip            0x5555555a8a69      0x5555555a8a69 <CServer::UpdateClientRconCommands()+399>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```
